### ISSUE TITLE
リファクタリング提案その１

### ISSUE THREAD

**Issue by pm-yosuke** [pressmaninc/mail-switcher-for-developer#1]
https://github.com/pressmaninc/mail-switcher-for-developer/blob/a2b1b39b04a15c1131813b910db18968362a2314/class/class-setting-option-page.php#L120-L121

`else` にたどり着くまでの `if/elseif` で全て `return` してるなら `else` はいらないです。

**Comment by katsunori-takahashi** [comment]
@pm-yosuke 
レビューありがとうございます！
不必要なのを確認いたしました。修正版を作成します。

**Comment by katsunori-takahashi** [comment]
@pm-yosuke 
本件は対応させていただいたので、クローズとさせて頂きます。
