### ISSUE TITLE
リファクタリング提案その２

### ISSUE THREAD

**Issue by pm-yosuke** [pressmaninc/mail-switcher-for-developer#2]
https://github.com/pressmaninc/mail-switcher-for-developer/blob/a2b1b39b04a15c1131813b910db18968362a2314/class/class-setting-option-page.php#L127-L141

エラーフラグ立てて `break` 後にエラー処理じゃなくてその場でエラー処理で良くない？

**Comment by katsunori-takahashi** [comment]
@pm-yosuke 
レビューありがとうございます！
確認をしたところ、必要ないフラグ処理でした。
修正版を作成いたします。

**Comment by katsunori-takahashi** [comment]
@pm-yosuke 
本件は対応させていただいたので、クローズとさせて頂きます。
